### ISSUE TITLE
Incomplete layout display in dialog box

### ISSUE THREAD

**Issue by BoyYangyang** [BrianTV98/slider_captcha#13]
![图片](https://user-images.githubusercontent.com/27199384/183851777-bd8bde45-7064-4f94-a82d-48d83d2720ba.png)

   showDialog(
                        context: context,
                        builder: (context) {
                          return AlertDialog(
                            shape:
                            RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                            contentPadding: EdgeInsets.zero,
                            content: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.circular(10),
                                  child: SliderCaptcha(
                                    controller: controller,
                                    image: Image.asset(
                                     R.assetsImagesTemporaryTemporary14,
                                      fit: BoxFit.contain,
                                    ),
                                    colorBar: Colors.blue,
                                    colorCaptChar: Colors.blue,
                                    onConfirm: (value) {
                                      if (!value) {
                                        controller.create();
                                      }
                                      print(value);
                                    },
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                      );

**Comment by BrianTV98** [comment]
@BoyYangyang  Thank you for commenting. AI will check and fix by the end of the week. Come back early next week and check back and early next week.

**Comment by BrianTV98** [comment]
Hi @BoyYangyang I was fixed your issue. You can check  again  in version 0.1.5.
Thank you. If you have any problem about this package. Please let me now.
