### ISSUE TITLE
The CaptCha puzzle is not visible when the page is accessed for the first time

### ISSUE THREAD

**Issue by hutomosaktikartiko** [BrianTV98/slider_captcha#17]
![Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 01 21](https://user-images.githubusercontent.com/51199036/190994927-91bf661f-709c-4e31-996a-eaae50e458e3.png)

This is my code
```
import 'package:flutter/material.dart';
import 'package:slider_captcha/slider_capchar.dart';

import 'shared/theme/custom_color.dart';

class TestPuzzle extends StatefulWidget {
  const TestPuzzle({Key? key}) : super(key: key);

  @override
  State<TestPuzzle> createState() => _TestPuzzleState();
}

class _TestPuzzleState extends State<TestPuzzle> {
  final SliderController _sliderController = SliderController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          SliderCaptcha(
            controller: _sliderController,
            image: Image.asset(
              'assets/images/data-empty.png',
              fit: BoxFit.fitWidth,
            ),
            colorBar: CustomColor.royalBlue70,
            colorCaptChar: Colors.black,
            title: "",
            onConfirm: (value) async {
              print(value);
              if (!value) {
                _sliderController.create();
              }
            },
          ),
        ],
      ),
    );
  }
}
```

When the page is hot-reloaded when development The CaptCha puzzle is available or by doing a random slider then the second slider The CaptCha puzzle is available

**Comment by BrianTV98** [comment]
@hutomosaktikartiko  thank your for contribute issue.  I will fix this issue in the next version.

**Comment by BrianTV98** [comment]
@hutomosaktikartiko  Hello. I have fixed the problem you are having. Please check the new version 0.1.7.

**Comment by hutomosaktikartiko** [comment]
@BrianTV98 I've checked the latest version, the previous bug was running smoothly. but the CaptCha puzzle appears like there is a millisecond delay, is that correct?

**Comment by BrianTV98** [comment]
@hutomosaktikartiko  The calculation of drawing and cutting the block is quite time consuming (about 0.01s). Developers will feel a slight delay when rendering the block. However this is completely imperceptible if you run the app with the release version

**Comment by hutomosaktikartiko** [comment]
I'm running in debug version, it deservers to feel long. But how about adding a loading widget while rendering process is in progress?

**Comment by BrianTV98** [comment]
@hutomosaktikartiko I feel it's unnecessary since the end goal is a release version. However, if you feel it is absolutely necessary for your application, create a new issue. I will help you to solve it
Creating a new issue will help the community reach the issue and avoid asking the same question again!
