### ISSUE TITLE
Flutter Web's CanvasKit with CupertinoApp Error: Could not find a set of Noto fonts to display all missing characters.

### ISSUE THREAD

**Issue by nemr0** [BrianTV98/slider_captcha#21]
I ran into this issue:
debug error: `Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts`
shows no slider icon:
<img width="247" alt="Screenshot 2023-03-29 at 2 37 56 AM" src="https://user-images.githubusercontent.com/60761933/228397279-b5c9f747-ed7a-4b4b-87cd-25caf4252ca3.png">

it only happens when building flutter web with canvaskit renderer.

works normally with html renderer:
<img width="290" alt="Screenshot 2023-03-29 at 2 42 45 AM" src="https://user-images.githubusercontent.com/60761933/228397581-fb48627a-6806-4d6a-9637-3ba567693b9d.png">

can you add a parameter for the icon? thanks for your help.

**Comment by BrianTV98** [comment]
@nemr0  Thank you for contributing an issue to this library.
I will update it in the next version.
Please come back to it early next week.

**Comment by nemr0** [comment]
Thanks for your fast replay🙏

**Comment by BrianTV98** [comment]
Dear @nemr0! 

I have updated version 0.1.10. Allowed to change slider icon.
If you find my library useful please like it on pubdev, github repo or donate to me via paypall. It will give me extra motivation to continue to develop and maintain the library throught [paypall](https://www.paypal.com/paypalme/tranhieuglpk)

**Comment by nemr0** [comment]
> Dear @nemr0! 
> 
> 
> 
> I have updated version 0.1.10. Allowed to change slider icon.
> 
> If you find my library useful please like it on pubdev, github repo or donate to me via paypall. It will give me extra motivation to continue to develop and maintain the library throught [paypall](https://www.paypal.com/paypalme/tranhieuglpk)

Thanks for your help❤️
