### ISSUE TITLE
Remove flutter_bloc dependency

### ISSUE THREAD

**Issue by limcheekin** [BrianTV98/slider_captcha#3]
Thanks for published the very useful package.

It will be great if you can remove the dependency to flutter_bloc package. 

As it will let the user decide what state management approach they wanted to adopt as there are plenty, 
please refer to the following URL:
https://docs.flutter.dev/development/data-and-backend/state-mgmt/options

**Comment by BrianTV98** [comment]
I will remove the dependency to flutter_bloc_package in the next version. 
 Thank you for your contribution.

**Comment by limcheekin** [comment]
By the way, the example is showcase at https://www.fluwix.com/slider_captcha_showcase
