### ISSUE TITLE
ui problem in tablet and mobile

### ISSUE THREAD

**Issue by flimuti** [BrianTV98/slider_captcha#5]
Hello,
I have tested the plugin on different sized devices. Everything is fine on a mobile device, but if I run the app on a tablet or browser it doesn't work well. There seems to be a problem with image fitting. I used the sample code.
Here are some screenshots of the result.
- mobile (all seems ok):
![image](https://user-images.githubusercontent.com/23105368/163139469-008aac73-7fbc-42f7-b2de-cf3ec576d392.png)
- tablet:
![image](https://user-images.githubusercontent.com/23105368/163140403-6dbd1623-1ed8-4bc9-b24e-45aa84c5a514.png)
- web (chrome):
![image](https://user-images.githubusercontent.com/23105368/163140936-2544e875-b076-4987-bcea-46046d1150b9.png)

Can you help me or fix the problem please? Thanks

**Comment by BrianTV98** [comment]
Thank you to  interest my package. I will check  your issue.
You can Come back next week and try the next version.

**Comment by BrianTV98** [comment]
@flimuti  
The variety of screen sizes makes it difficult for me to create new captchars. So I decided to limit the maximum horizontal size for the library to 500 dp. The image will be filled to this size.
