### ISSUE TITLE
customize text on 5  wrong swipes

### ISSUE THREAD

**Issue by YouSour** [BrianTV98/slider_captcha#7]
hi, how could i customize text on 5  wrong swipes ? thank in advance 😄 

![Screen Shot 2022-05-20 at 9 19 31 AM](https://user-images.githubusercontent.com/9318106/169436201-52b2fc38-bed3-46e5-8102-afaf90418541.png)

**Comment by mikedevt2** [comment]
@BrianTV98 Is there a way to change the wrong swipe title mentioned above?

Thanks!

**Comment by BrianTV98** [comment]
@mikedevt2 , @YouSour  . 
Thanks for commenting on my package
I think it is too rigid for my library to manage the screen failure. So I decided to remove it. Instead I added in **SliderController**. Now, when you finish dragging the slider bar, the UI will no longer automatically update and create a new Captchar. You can get the result of the drag and drop via the **onConfirm** method. And create new captchar through controller. So users can be more comfortable to customize what they want. You can lock your screen your way through flutter's **AbsorbPointer** tag, and overwrite the content you want via the **Stack** tag
