### ISSUE TITLE
return value on success from user swipe

### ISSUE THREAD

**Issue by YouSour** [BrianTV98/slider_captcha#8]
hi, i think u should return value on success from user swipe into the right position, sometime it can be helpful.

**Comment by BrianTV98** [comment]
@YouSour  I agree with this opinion. In the last update. I have removed the failure status too much. Instead I added OnConfirm which returns the status of the validation. The creation of a new captchar will be decided by the terminal application developer, through the controller.

Thank you for contributing  issue to my package
